import type { Metadata } from "next";
import { StubPage } from "../stub";

export const metadata: Metadata = {
  title: "Press kit",
  description:
    "Press assets, one-paragraph pitch, founder story, and contact for Hardenator.",
};

export default function PressPage() {
  return (
    <StubPage
      eyebrow="Press kit"
      title="For writers covering vibe-coded app security."
      lead="Everything you need to cover Hardenator accurately. Reach out first if anything is unclear — we respond fast."
      body={
        <>
          <h2
            style={{
              fontFamily: "var(--font-fraunces), serif",
              fontWeight: 900,
              fontSize: 22,
              margin: "24px 0 12px",
            }}
          >
            One-paragraph pitch
          </h2>
          <p style={{ marginBottom: 24 }}>
            Hardenator is the security OS for AI-generated code. A Semgrep-based
            static analyzer plus LLM-driven auto-fix layer that intercepts
            insecure code at generation time — inside Claude Code, Cursor,
            Lovable, Bolt, v0, Replit, Codex, and Devin — instead of waiting
            for the six-week-post-ship breach. Open-source rule library, MIT.
            Founded by Lingesh Balasubramaniam, April 2026, Kuala Lumpur.
          </p>

          <h2
            style={{
              fontFamily: "var(--font-fraunces), serif",
              fontWeight: 900,
              fontSize: 22,
              margin: "24px 0 12px",
            }}
          >
            Why now
          </h2>
          <ul style={{ paddingLeft: 20, marginBottom: 24 }}>
            <li style={{ marginBottom: 8 }}>
              91.5% of vibe-coded apps have at least one AI-hallucination
              vulnerability (Q1 2026 study, 200+ apps).
            </li>
            <li style={{ marginBottom: 8 }}>
              AI-written code has a 2.74× vulnerability rate vs human-written
              (arXiv, 470 GitHub PRs).
            </li>
            <li style={{ marginBottom: 8 }}>
              Three major Lovable breaches in thirteen months — Jan 2026
              Moltbook, Feb 2026 education app, April 2026 mass breach.
            </li>
            <li style={{ marginBottom: 8 }}>
              Gartner forecast: 60% of all new code will be AI-generated by
              end of 2026.
            </li>
          </ul>

          <h2
            style={{
              fontFamily: "var(--font-fraunces), serif",
              fontWeight: 900,
              fontSize: 22,
              margin: "24px 0 12px",
            }}
          >
            Founder
          </h2>
          <p style={{ marginBottom: 24 }}>
            Lingesh Balasubramaniam. Solo founder, Kuala Lumpur. Background in
            electrical power engineering; decade of technical work, most of it
            on industrial systems. Built Hardenator after auditing his own
            vibe-coded SaaS (Resillator) and finding a dozen-plus security
            holes he hadn&apos;t thought to look for.
          </p>

          <h2
            style={{
              fontFamily: "var(--font-fraunces), serif",
              fontWeight: 900,
              fontSize: 22,
              margin: "24px 0 12px",
            }}
          >
            Contact
          </h2>
          <p style={{ marginBottom: 12 }}>
            <a
              href="mailto:press@hardenator.com"
              style={{ color: "var(--ink)", textDecoration: "underline" }}
            >
              press@hardenator.com
            </a>{" "}
            — typically within 24 hours.
          </p>

          <p style={{ marginBottom: 12, color: "var(--whisper)", fontSize: 14 }}>
            Logos + screenshots + founder photo land on this page the week of
            Apr 28.
          </p>
        </>
      }
    />
  );
}
